//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.CrossCutting {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.CrossCutting.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your activity:
        ///1 - Get all vacations
        ///2 - Get vacation
        ///3 - Add vacation
        ///4 - Delete vacation
        ///5 - Update vacation
        ///6 - Connect/disconnect to Internet
        ///7 - Exit.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorization is faild. 
        ///Please, enter correct login and password.
        /// </summary>
        internal static string AutorizationFaild {
            get {
                return ResourceManager.GetString("AutorizationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 0 for cansel.
        /// </summary>
        internal static string CanselOperation {
            get {
                return ResourceManager.GetString("CanselOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have connection to Internet?
        ///Please, choose: 1 - Yes, 2 - No.
        /// </summary>
        internal static string ConnectToInternet {
            get {
                return ResourceManager.GetString("ConnectToInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter CreatedBy.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which Vacation you want delete:.
        /// </summary>
        internal static string DeleteVacation {
            get {
                return ResourceManager.GetString("DeleteVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptional Leave.
        /// </summary>
        internal static string Exceptional {
            get {
                return ResourceManager.GetString("Exceptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which Vacation you want get:.
        /// </summary>
        internal static string GetVacation {
            get {
                return ResourceManager.GetString("GetVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to VTS system.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Without Pay.
        /// </summary>
        internal static string LeaveWithoutPay {
            get {
                return ResourceManager.GetString("LeaveWithoutPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your login:.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        internal static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You secsessfull login.
        /// </summary>
        internal static string SecsessfullLogin {
            get {
                return ResourceManager.GetString("SecsessfullLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick days.
        /// </summary>
        internal static string Sick {
            get {
                return ResourceManager.GetString("Sick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Start Date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which Vacation you want update:.
        /// </summary>
        internal static string UpdateVacation {
            get {
                return ResourceManager.GetString("UpdateVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Vacation Status
        ///1 - Draft
        ///2 - Submitted
        ///3 - Approved
        ///4 - InProgress
        ///5 - Closed.
        /// </summary>
        internal static string VacationStatus {
            get {
                return ResourceManager.GetString("VacationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Vacation Type
        ///1 - Undefined
        ///2 - Regular
        ///3 - Sick
        ///4 - Exceptional
        ///5 - LeaveWithoutPay
        ///6 - Overtime.
        /// </summary>
        internal static string VacationType {
            get {
                return ResourceManager.GetString("VacationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want connection to Internet?
        ///Please, choose: 1 - Yes, 2 - No.
        /// </summary>
        internal static string WantConnectToInternet {
            get {
                return ResourceManager.GetString("WantConnectToInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want disconnection to Internet?
        ///Please, choose: 1 - Yes, 2 - No.
        /// </summary>
        internal static string WantDisconnectToInternet {
            get {
                return ResourceManager.GetString("WantDisconnectToInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose what you want change:
        ///1 - Start Date
        ///2 - End Date
        ///3 - Vacation Type
        ///4 - Vacation Status.
        /// </summary>
        internal static string WhatChange {
            get {
                return ResourceManager.GetString("WhatChange", resourceCulture);
            }
        }
    }
}
